working_directory = "sites"

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
startup_mode="Maximized"
decorations = "Buttonless"
opacity = 0.7
blur = true

option_as_alt = "Both"

[font]
normal.family = "GeistMono Nerd Font"

size = 18
